version: '3.8'

services:
  db:
    image: postgres
    restart: 'no'
    environment:
      POSTGRES_DB: ${DATABASE_DB:-postitquick}
      POSTGRES_USER: ${DATABASE_USER:-application}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-9ia6QDzoCzcbpwRnu5qyrKyzKcxfiMpP}
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
