import { RolesBuilder } from 'nest-access-control';

import { AUTHORIZATION_RESOURCE } from './authorizationResource.constant';
import { AUTHORIZATION_ROLE } from './authorizationRole.constant';

export const AUTHORIZATION_GRANT = new RolesBuilder();

AUTHORIZATION_GRANT.grant(AUTHORIZATION_ROLE.USER)
  .updateOwn(AUTHORIZATION_RESOURCE.USER)
  .deleteOwn(AUTHORIZATION_RESOURCE.USER)
  .readAny(AUTHORIZATION_RESOURCE.USER);

AUTHORIZATION_GRANT.grant(AUTHORIZATION_ROLE.USER)
  .updateOwn(AUTHORIZATION_RESOURCE.PROFILE)
  .readAny(AUTHORIZATION_RESOURCE.PROFILE);

AUTHORIZATION_GRANT.grant(AUTHORIZATION_ROLE.USER)
  .createOwn(AUTHORIZATION_RESOURCE.POST)
  .updateOwn(AUTHORIZATION_RESOURCE.POST)
  .deleteOwn(AUTHORIZATION_RESOURCE.POST)
  .readAny(AUTHORIZATION_RESOURCE.POST);

export class AuthorizationGrant extends RolesBuilder {}
